function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{typeof(buildcolumns),Nothing,T<:(Tables.IteratorWrapper{_A} where _A)})   # time: 0.2143485
    Base.precompile(Tuple{typeof(buildcolumns),Any,IteratorWrapper{_A} where _A})   # time: 0.0516712
    Base.precompile(Tuple{typeof(allocatecolumns),Schema{(:year, :selfemployed, :hasinsurance, :post, :post_self), Tuple{Union{Missing, Float32}, Union{Missing, Int8}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}}},Int64})   # time: 0.0498734
    Base.precompile(Tuple{typeof(allocatecolumns),Schema{(:name, :id_split, :fid_843_gr, :pixcluster, :pixwbcode, :pixlat, :pixlon, :pixwater, :pixnmbrdia, :pixnmbrpetro, :lnkm, :pixpetro, :pixdia, :pixwaterd, :pixcapdist, :pixmal, :pixsead, :pixsuit, :pixelev, :pixbdist, :pd0, :lnpd0, :l0708, :l0708d, :lnl0708s, :lnwaterkm, :km2split, :lnkm2split, :wbcode, :mean_elev, :mean_suit, :malariasuit, :petroleum, :diamondd, :capdistance1, :seadist1, :borderdist1, :centr_tribe, :gr, :unique, :centr_tribe1), Tuple{Union{Missing, String}, Union{Missing, Int16}, Union{Missing, Int32}, Union{Missing, String}, Union{Missing, String}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, String}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, Float32}, Union{Missing, String}, Union{Missing, Float32}}},Int64})   # time: 0.0226381
    Base.precompile(Tuple{typeof(allocatecolumns),Schema{(:idcode, :age, :race, :married, :never_married, :grade, :collgrad, :south, :smsa, :c_city, :industry, :occupation, :union, :wage, :hours, :ttl_exp, :tenure), Tuple{Union{Missing, Int16}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Int8}, Union{Missing, Float32}, Union{Missing, Int8}, Union{Missing, Float32}, Union{Missing, Float32}}},Int64})   # time: 0.0177316
    Base.precompile(Tuple{typeof(allocatecolumns),Schema{(:coll, :merit, :male, :black, :asian, :year, :state, :chst), NTuple{8, Union{Missing, Float32}}},Int64})   # time: 0.0154631
    Base.precompile(Tuple{typeof(schema),IteratorWrapper{_A} where _A})   # time: 0.0064134
    Base.precompile(Tuple{Type{Schema},Vector{Symbol},Vector{DataType}})   # time: 0.0036888
    Base.precompile(Tuple{typeof(which(_columntable,(Tables.Schema{names, types},Any,)).generator.gen),Any,Any,Any,Any,Any})   # time: 0.0025184
    Base.precompile(Tuple{typeof(columnnames),CopiedColumns{NamedTuple{(:year, :selfemployed, :hasinsurance, :post, :post_self), Tuple{Vector{Union{Missing, Float32}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}}}}})   # time: 0.0019326
    Base.precompile(Tuple{typeof(columnnames),CopiedColumns{NamedTuple{(:name, :id_split, :fid_843_gr, :pixcluster, :pixwbcode, :pixlat, :pixlon, :pixwater, :pixnmbrdia, :pixnmbrpetro, :lnkm, :pixpetro, :pixdia, :pixwaterd, :pixcapdist, :pixmal, :pixsead, :pixsuit, :pixelev, :pixbdist, :pd0, :lnpd0, :l0708, :l0708d, :lnl0708s, :lnwaterkm, :km2split, :lnkm2split, :wbcode, :mean_elev, :mean_suit, :malariasuit, :petroleum, :diamondd, :capdistance1, :seadist1, :borderdist1, :centr_tribe, :gr, :unique, :centr_tribe1), Tuple{Vector{Union{Missing, String}}, Vector{Union{Missing, Int16}}, Vector{Union{Missing, Int32}}, Vector{Union{Missing, String}}, Vector{Union{Missing, String}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, String}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, String}}, Vector{Union{Missing, Float32}}}}}})   # time: 0.0017221
    Base.precompile(Tuple{typeof(columnnames),CopiedColumns{NamedTuple{(:coll, :merit, :male, :black, :asian, :year, :state, :chst), NTuple{8, Vector{Union{Missing, Float32}}}}}})   # time: 0.0017163
    Base.precompile(Tuple{typeof(columnnames),CopiedColumns{NamedTuple{(:idcode, :age, :race, :married, :never_married, :grade, :collgrad, :south, :smsa, :c_city, :industry, :occupation, :union, :wage, :hours, :ttl_exp, :tenure), Tuple{Vector{Union{Missing, Int16}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Int8}}, Vector{Union{Missing, Float32}}, Vector{Union{Missing, Float32}}}}}})   # time: 0.0015861
    Base.precompile(Tuple{Type{CopiedColumns},NamedTuple})   # time: 0.0015302
end
